---
- name: 'Bootstrap Proxmox on Dell T7600'
  hosts: pve
  remote_user: root
  vars_files:
    - vars/packages.yml
    - vars/secret.yml

  pre_tasks:

  - name: 'create interactive user user'
    user:
      name: '{{ interactive_user }}'
      password: '{{ interactive_password | password_hash("sha512") }}'
      shell: /bin/bash
      groups: sudo
      append: true

  roles:

    - role: ironicbadger.proxmox_nag_removal

    - role: update-debian

    - role: geerlingguy.docker
      vars:
        # ensure `docker compose` can be used
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
        docker_users:
          '{{ interactive_user }}'

  post_tasks:

    - name: 'install packages'
      package:
        name: '{{ install_packages }}'
        state: latest
